// Copyright 2026 The runZero contributors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package ssl2

// HandshakeLog records every SSL 2.0 handshake message observed on a
// [Conn], plus the symmetric keying material derived during key exchange.
// It is intended for diagnostic / audit / scan-output use; the secret
// fields are populated to allow offline replay analysis.
//
// Fields are populated incrementally:
//   - [Conn.Probe] populates ClientHello, ServerHello, and (if the peer
//     responded with an ERROR record) ServerError.
//   - [Conn.Handshake] / [Conn.HandshakeWithConfig] populates the
//     remaining fields (ClientMasterKey, key material, ServerVerify,
//     ClientFinished, ServerFinished, optional REQUEST-CERTIFICATE /
//     CLIENT-CERTIFICATE pair, and SelectedCipher).
type HandshakeLog struct {
	// Wire messages, in order they appeared on the wire.
	ClientHello        *ClientHello        `json:"client_hello,omitempty"`
	ServerHello        *ServerHello        `json:"server_hello,omitempty"`
	ServerError        *ServerError        `json:"server_error,omitempty"`
	ClientMasterKey    *ClientMasterKey    `json:"client_master_key,omitempty"`
	ServerVerify       *ServerVerify       `json:"server_verify,omitempty"`
	ClientFinished     *ClientFinished     `json:"client_finished,omitempty"`
	ServerFinished     *ServerFinished     `json:"server_finished,omitempty"`
	RequestCertificate *RequestCertificate `json:"request_certificate,omitempty"`
	ClientCertificate  *ClientCertificate  `json:"client_certificate,omitempty"`

	// SelectedCipher is the cipher kind ultimately chosen by the client
	// in CLIENT-MASTER-KEY (echoed by the server in SERVER-VERIFY).
	SelectedCipher CipherKind `json:"selected_cipher,omitempty"`

	// Challenge is the bytes the client sent in CLIENT-HELLO. Stored
	// here for convenience because the server's SERVER-VERIFY message
	// must echo this back.
	Challenge []byte `json:"challenge,omitempty"`

	// KeyMaterial holds the keys derived during the SSL 2.0 handshake.
	// Includes both the master key (sent partly in clear, partly RSA-
	// encrypted in CLIENT-MASTER-KEY) and the per-direction symmetric
	// keys produced by the SSL 2.0 KDF.
	KeyMaterial *SSLv2KeyMaterial `json:"key_material,omitempty"`
}

// SSLv2KeyMaterial holds the symmetric keying material derived during an
// SSL 2.0 handshake.
type SSLv2KeyMaterial struct {
	// MasterKey is CLEAR-KEY || SECRET-KEY, the full master key as
	// generated by the client.
	MasterKey []byte `json:"master_key,omitempty"`
	// ClearKey is the clear portion of MasterKey, sent verbatim in
	// CLIENT-MASTER-KEY.clear_key.
	ClearKey []byte `json:"clear_key,omitempty"`
	// SecretKey is the secret portion of MasterKey, RSA-encrypted under
	// the server's certificate and sent in CLIENT-MASTER-KEY.encrypted_key.
	SecretKey []byte `json:"secret_key,omitempty"`
	// KeyArg is the IV transmitted in CLIENT-MASTER-KEY.key_arg for
	// block ciphers (CBC), or nil for stream ciphers.
	KeyArg []byte `json:"key_arg,omitempty"`
	// ClientWriteKey is the symmetric key the client uses to encrypt
	// (and the server uses to decrypt) records in the
	// client-to-server direction.
	ClientWriteKey []byte `json:"client_write_key,omitempty"`
	// ServerWriteKey is the symmetric key the server uses to encrypt
	// (and the client uses to decrypt) records in the
	// server-to-client direction.
	ServerWriteKey []byte `json:"server_write_key,omitempty"`
}

// GetHandshakeLog returns the HandshakeLog accumulated on this connection
// (or nil if no handshake activity has occurred). The returned pointer
// is the live log; callers must not mutate it concurrently with
// [Conn.Probe] / [Conn.Handshake].
func (c *Conn) GetHandshakeLog() *HandshakeLog {
	c.mu.Lock()
	defer c.mu.Unlock()
	return c.handshakeLog
}

// log returns (and lazily initializes) the connection's HandshakeLog.
func (c *Conn) log() *HandshakeLog {
	if c.handshakeLog == nil {
		c.handshakeLog = &HandshakeLog{}
	}
	return c.handshakeLog
}
