// Copyright 2026 The excrypto Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Helpers that convert key-agreement state into JSON-marshalable
// handshake-log entries. Ported from
// github.com/runZeroInc/excrypto/crypto/ssl3/tls/tls_ka.go and adapted
// to the modern crypto/tls field layout (no DHE; ECDHE bytes-only).

package tls

import (
	"math/big"
	"strconv"

	jsonKeys "github.com/runZeroInc/excrypto/crypto/json"
)

// DigitalSignature represents a TLS digitally-signed-struct from a
// TLS 1.0–1.2 ServerKeyExchange. In TLS 1.2 the first two octets of the
// raw signature carry the SignatureAndHashAlgorithm pair; in older
// versions they do not.
type DigitalSignature struct {
	Raw              []byte            `json:"raw,omitempty"`
	Type             string            `json:"type,omitempty"`
	Valid            bool              `json:"valid"`
	SigHashExtension *SignatureAndHash `json:"signature_and_hash_type,omitempty"`
	Version          LoggedTLSVersion  `json:"tls_version"`
}

// signatureTypeToName maps the modern crypto/tls internal signature-type
// enum (signaturePKCS1v15 / signatureRSAPSS / signatureECDSA / signatureEd25519)
// onto the human names ssl3/tls used.
func signatureTypeToName(sigType uint8) string {
	switch sigType {
	case signaturePKCS1v15, signatureRSAPSS:
		return "rsa"
	case signatureECDSA:
		return "ecdsa"
	case signatureEd25519:
		return "ed25519"
	}
	return "unknown." + strconv.Itoa(int(sigType))
}

// sigTypeForClientCertificateRequest and hashForClientCertificateRequest
// are defined in excrypto_compat.go. We reuse those helpers.

// digitalSignatureFromKA captures a [DigitalSignature] from an ECDHE key
// agreement (the only signed key exchange the modern stack supports).
func digitalSignatureFromKA(ka *ecdheKeyAgreement) *DigitalSignature {
	if ka == nil {
		return nil
	}
	out := &DigitalSignature{
		Raw:     append([]byte(nil), ka.excryptoSig...),
		Type:    signatureTypeToName(ka.excryptoSigType),
		Valid:   ka.excryptoSigValid,
		Version: LoggedTLSVersion(ka.version),
	}
	if ka.version >= VersionTLS12 {
		out.SigHashExtension = &SignatureAndHash{
			Signature: sigTypeForClientCertificateRequest(ka.excryptoSigType),
			Hash:      hashForClientCertificateRequest(ka.excryptoSigHash),
		}
	}
	return out
}

// ecdheParamsFromKA captures the server-side ECDHE parameters as observed
// by a TLS client during processServerKeyExchange.
func ecdheParamsFromKA(ka *ecdheKeyAgreement) *jsonKeys.ECDHParams {
	if ka == nil {
		return nil
	}
	out := &jsonKeys.ECDHParams{TLSCurveID: jsonKeys.TLSCurveID(ka.curveID)}
	if pt := ecPointFromBytes(ka.excryptoServerPub); pt != nil {
		out.ServerPublic = pt
	}
	return out
}

// ecdheClientParamsFromKA captures the client-side ECDHE parameters as
// generated by the local client (for handshake logging).
func ecdheClientParamsFromKA(ka *ecdheKeyAgreement) *jsonKeys.ECDHParams {
	if ka == nil {
		return nil
	}
	out := &jsonKeys.ECDHParams{TLSCurveID: jsonKeys.TLSCurveID(ka.curveID)}
	if pt := ecPointFromBytes(ka.excryptoClientPub); pt != nil {
		out.ClientPublic = pt
	}
	return out
}

// ecPointFromBytes converts a TLS-wire EC point (uncompressed: 0x04 || X
// || Y, or X25519/X448 raw scalar) into a [jsonKeys.ECPoint]. For
// curves without a Y coordinate (X25519/X448) only ECPoint.X is set,
// holding the raw public-key bytes interpreted as a big-endian integer.
// Returns nil for empty input.
func ecPointFromBytes(b []byte) *jsonKeys.ECPoint {
	if len(b) == 0 {
		return nil
	}
	// Uncompressed NIST point: 0x04 || X || Y, X and Y equal length.
	if b[0] == 0x04 && (len(b)-1)%2 == 0 {
		half := (len(b) - 1) / 2
		return &jsonKeys.ECPoint{
			X: new(big.Int).SetBytes(b[1 : 1+half]),
			Y: new(big.Int).SetBytes(b[1+half:]),
		}
	}
	// Otherwise (X25519/X448 or compressed point) stuff bytes into X.
	return &jsonKeys.ECPoint{X: new(big.Int).SetBytes(b)}
}
